### ISSUE TITLE
 Support projects with custom modules `projectDir` settings

### ISSUE THREAD

**Issue by AraujoJordan** [getyourguide/paparazzi-plugin#10]
## Context
Some projects, for better organization, adds modules in the `settings.gradle` file with a custom `projectDir`. This allows better organization as we can add similar context modules to a common folder inside the parent project.

For example, you can use this: 

```kotlin
fun includeModule(module: String, path: String? = null) {
    val moduleName = ":$module"
    include(moduleName)
    project(moduleName).apply {
        buildFileName = "$module.build.gradle.kts"
        path?.run {
            projectDir = File(path)
        }
    }
}
```

## Problem description

Currently, the way that `paparazzi-plugin` works to find a path of a module [modulePath()](https://github.com/getyourguide/paparazzi-plugin/blob/7fcca15d0197bf9a791eab81b9368fa10dcf49aa/src/main/kotlin/com/getyourguide/paparazzi/Utils.kt#L57C1-L57C1) is not aware that a module could be inside a sub-folder or using other custom gradle module folder configuration.

## Solution (suggestion)

One simple way to fix this is to, instead the current implementation of get the first segment of the relative path of the `file` argument, we can actually search where the file is inside the `Project.modules`, and than, extract the module path with `getModuleDir()`:

```kotlin
/**
 * Get the test module path that contains the file, searching in all project test modules.
 */
internal fun Project.modulePath(file: VirtualFile): String? {
    return modules
        .asSequence()
        .filter { it.isTestModule }
        .firstOrNull { File(it.getModuleDir()).walk().find { it.path == file.path } != null }
        ?.getModuleDir()
}
```

We can improve it even better by using the module path to match the file path prefix. Removing that `walk().find()` functions.

**Comment by thsaravana** [comment]
I will take a look at this.
You should be able to contribute to the `main` branch. Just fork this repo, make the changes and raise a PR against the `main` branch.

**Comment by AraujoJordan** [comment]
@thsaravana Done!
