### ISSUE TITLE
Error recording test

### ISSUE THREAD

**Issue by mshearer123** [getyourguide/paparazzi-plugin#8]
Hi,

plugin looks great, nice work.

We've an issue running it on our app

```
Project directory '/Users/xxx/Repos/xxx/xxx/moduleName' is not part of the build defined by settings file '/Users/xxx/Repos/xxx/xxx/settings.gradle.kts'. If this is an unrelated build, it must have its own settings file.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
```

I presume this is because we automatically scan directories to add modules to the project.

```
file("common").safeListFiles { dir ->
  include("common-${dir.name}")
  project(":common-${dir.name}").projectDir = dir
}
```

Can anything be done?

thanks

**Comment by thsaravana** [comment]
This looks like a problem with gradle settings in the project, and less related to the plugin itself. The plugin essentially runs the `recordPaparazziDebug` gradle task.
I suggest you raise this query with the Gradle or the Paparazzi project. You will get faster answers there.
